[versions]
agp = "8.6.0"
kotlin = "2.0.21"

core-ktx = "1.13.1"
lifecycle-runtime-ktx = "2.8.6"

android-jvm = "17"
android-compileSdk = "34"
android-targetSdk = "34"
android-minSdk = "26"

androidx-core-splashscreen = "1.0.1"

compose-bom = "2024.09.03"  
compose-activity = "1.9.2"
compose-navigation = "2.8.2"
compose-material-motion = "2.0.1"
compose-material-icons = "1.7.3"
compose-viewmodel = "2.8.6"
compose-tabler-icons = "1.1.1"

[plugins]
agp-library = { id = "com.android.library", version.ref = "agp" }
agp-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics"}
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-viewmodel" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-material-motion-core = { group = "io.github.fornewid", name = "material-motion-compose-core", version.ref = "compose-material-motion" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-material-icons" }
compose-tabler-icons = { group = "br.com.devsrsouza.compose.icons", name = "tabler-icons", version.ref = "compose-tabler-icons" }

# Android X Core
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }

# KotlinX
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }